# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='ImageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('imagedoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docservice.ImageDocument')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('createdDate', models.DateTimeField()),
                ('modifiedDate', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.FileField(upload_to=b''),
        ),
    ]
