# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docservice', '0002_auto_20170517_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetype',
            name='imagedoc',
        ),
        migrations.AddField(
            model_name='imagetype',
            name='imageDoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docservice.ImageDocument'),
        ),
        migrations.AlterField(
            model_name='imagedocument',
            name='upload',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
