# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docservice', '0003_auto_20170517_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedocument',
            name='upload',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
